name: Python package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Poetry Lock
      run: poetry lock
    - name: Poetry Install
      run: poetry install
    - name: Black
      run: poetry run python -m black .
    - name: Dephell Convert
      run: poetry run python -m dephell convert
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "build"    
    - name: Lint
      run: poetry run python -m flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Test
      run: poetry run python -m pytest --cov=simple_back --cov-branch tests/
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
