name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - uses: dschep/install-poetry-action@v1.3
    - name: Poetry Lock
      run: poetry lock
    - name: Poetry Install
      run: poetry install
    - name: requirements.txt
      run: poetry run pip freeze | awk '/==/' > requirements.txt
    - name: requirements-docs.txt
      run: poetry run pip freeze | awk '/sphinx|Sphinx/' > docs/requirements.txt
    - name: Black
      run: poetry run python -m black .
    - name: Dephell Convert
      run: poetry run python -m dephell convert
    - name: Replace Notebook References
      run: poetry run bash -c "cd docs/scripts && make html && python replace_nbsphinx_ref.py"
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: "build"    
    - name: Lint
      run: poetry run python -m flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Test
      run: poetry run python -m pytest --cov=simple_back --cov-branch --cov-report=xml tests/
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
